id: IDC9A8458
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:08:02+00:00'
last_modified: '2022-06-08T06:20:04.060691+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29015
  title: གསུང་འབུམ། བཟང་པོ་བཀྲ་ཤིས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E44C:
      image_group_id: I5014
      title: ''
      total_pages: 700
      order: 1
      base_file: E44C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
